project:
  type: book
  output-dir: docs

book:
  title: "Adriel Nathanael Simatupang"
  subtitle: "Portfolio Asesmen II-2100 KIPP"
  author: "18224109 Adriel N S"
  date: "10/20/2025"
  chapters:
    - index.qmd
    - My_Song_for_You/index.qmd
    - My_Stories_for_You/index.qmd
    - My_Shapes/index.qmd
    - My_Personal_Reviews/index.qmd
    - My_Concepts/index.qmd
    - My_Opinions/index.qmd
    - My_Innovations/index.qmd
    - My_Knowledge/index.qmd
    - My_Professional_Reviews/index.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



