# - My Songs for You
    
>**For Those Who Made Me Who I Am Now**

## For Myself 
### Madeon, EARTHGANG - No Fear No More (Remix) {.unnumbered}
*"Congratulations, you've made it this far!"*
{{< video https://www.youtube.com/watch?v=kGQet-Wgf5A>}}


Lagu ini mengingatkan saya bahwa hidup adalah sebuah *marathon*, bukan *sprint*.  
Sering kali saya merasa tidak ada kemajuan berarti dalam keseharian, seolah saya terus berada di titik yang sama. Namun, lagu ini mengingatkan bahwa setiap langkah kecil tetap memiliki makna — bahwa proses yang panjang dan konsistenlah yang membawa saya sampai ke titik ini.

Perjalanan hidup bukan tentang siapa yang paling cepat mencapai tujuan, melainkan tentang bagaimana seseorang mampu terus bertahan, belajar, dan berkembang di sepanjang jalan.  
Jika saya mampu mencapai sejauh ini, maka tidak ada alasan untuk meragukan langkah-langkah berikutnya.

> “When you make it this far is it ever done?”  
>
> “Good news, the best is yet to come.”

Setiap kali mendengarkan lagu ini, saya merasa diingatkan untuk tetap tenang dan percaya pada proses.  
Bahwa selama saya terus berusaha dan tidak berhenti berjalan, hal-hal baik akan selalu menanti di depan.


## For My Friends and Family
### Ben E. King - Stand By Me {.unnumbered}
*"What would I be without you guys?"*
{{< video https://www.youtube.com/watch?v=z5i9vT8wGY8>}}


Lagu ini adalah lagu klasik tentang pertemanan, tapi meskipun lagu ini sudah berumur lebih dari enam dekade, pesannya tetap sama, yaitu tentang kesetiaan dan kebersamaan yang tidak lekang oleh waktu.

Bagi saya, *Stand By Me* bukan sekadar lagu lama, tapi pengingat bahwa di balik setiap perjalanan dan tantangan, selalu ada orang-orang yang tetap berada di sisi kita.  
Mereka yang hadir bukan karena segalanya mudah, tapi karena hubungan itu berharga.

> “No, I won’t be afraid, just as long as you stand by me.”

Bersama teman dan keluarga, saya belajar bahwa kekuatan sejati tidak selalu datang dari diri sendiri, melainkan dari kehadiran mereka yang selalu ada untuk saya.


## For My Special Someone
###  d4v4 - Here With Me {.unnumbered}
*"Thank you for being in my life..."*
{{< video https://www.youtube.com/watch?v=B7Y4LHbpXv0>}}


Satu hal yang cukup mengagetkan tentang lagu ini, yaitu penyanyi dari lagu ini (d4vd) baru saja terkena kasus yang cukup kontroversial. Meskipun demikian, menurut saya, isi dari lagu ini tetaplah sesuatu yang sangat merepresentasikan perasaan saya tentang pasangan saya. 

> "I don't care how long it takes"
>
> "As long as I'm with you I've got a smile on my face"
>
> "Save your tears, it'll be okay"
>
> "You're here with me"

Dalam menjalin hubungan dengan seseorang, saya berpegang kepada satu hal, yaitu **komitmen**. Artinya, saya telah menerima pasangan saya apa adanya dan saya akan melakukan segalanya untuk bisa bersamanya sampai akhir.



